### ISSUE TITLE
Option to disable `kmesg` and `syslog` tailer

### ISSUE THREAD

**Issue by ConnorRigby** [nerves-project/nerves_runtime#100]
### Current behavior
When starting `nerves_runtime` on a `host` machine. (for example when testing NervesHub) 
The application fails to start:
```
kmsg_tailer: open /proc/kmsg: Permission denied

13:42:47.743 [info]  Application nerves_runtime exited: Nerves.Runtime.Application.start(:normal, []) returned an error: shutdown: failed to start child: Nerves.Runtime.Log.SyslogTailer
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, :eaddrinuse}
            (nerves_runtime) lib/nerves_runtime/log/syslog_tailer.ex:26: Nerves.Runtime.Log.SyslogTailer.init/1
            (stdlib) gen_server.erl:374: :gen_server.init_it/2
            (stdlib) gen_server.erl:342: :gen_server.init_it/6
            (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
** (Mix) Could not start application nerves_runtime: Nerves.Runtime.Application.start(:normal, []) returned an error: shutdown: failed to start child: Nerves.Runtime.Log.SyslogTailer
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, :eaddrinuse}
            (nerves_runtime) lib/nerves_runtime/log/syslog_tailer.ex:26: Nerves.Runtime.Log.SyslogTailer.init/1
            (stdlib) gen_server.erl:374: :gen_server.init_it/2
            (stdlib) gen_server.erl:342: :gen_server.init_it/6
            (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3

```

### Expected behavior
To be able to start `nerves_runtime` on host machine

### Proposed solution:
Currently one can disable some things with configs such as:

```
config :nerves_runtime, :kernel,
  autoload_modules: false
```

I think something like 
```
config :nerves_runtime, Nerves.Runtime.Log,
   kmesg_tailer: false,
   syslog_tailer: false
```
Would work fine?

**Comment by fhunleth** [comment]
I'm not a fan of all of the piecemeal disable feature options. Normally I like the fine grain capability, but I think for `nerves_runtime` there's no use case for a partial configuration. It's either on target or on host. 

I think this needs to be revisited, but there's a `:target` config option that I'd prefer everything check. See https://github.com/nerves-project/nerves_runtime/blob/master/lib/nerves_runtime.ex#L76-L79. 

My vote would be to check that for whether to enable the tailers and then in another PR, remove `autoload_modules`. Elixir 1.8 is supposed to have first class support for targets and I would expect that we refactor whatever we have to use that when it's available.

**Comment by fhunleth** [comment]
@mobileoverlord Pinging you on this issue, since you have more insight into what's happening with Elixir 1.8 and how that will or will not affect `nerves_runtime`. My comments are above. I still feel the same way that `nerves_runtime` should do the right thing by default when compiling for the host. Since writing the above comment, I don't mind if there's fine grain tuning of options.

**Comment by mobileoverlord** [comment]
@ConnorRigby `nerves_runtime` organizes its main supervisor to switch based off the target being passed down in the config. This was done this way because the env var `MIX_TARGET` was not concrete. 

Official support for `MIX_TARGET` is scheduled for Elixir 1.8. 
https://github.com/elixir-lang/elixir/issues/8063

Until then, we need to pass it forward.
https://github.com/nerves-hub/nerves_hub/pull/35

**Comment by michaelkschmidt** [comment]
Is there a reason you don't want to use "sudo" to be able to read those on host?  Just curious...

**Comment by ConnorRigby** [comment]
I really hate when libraries make it their decision to use `sudo`, but also most user's `sudo`
requires intervention, which would be irritating and also kind of cumbersome.

**Comment by michaelkschmidt** [comment]
Fair enough
