### ISSUE TITLE
Interactive host shell returns to prompt while OS process is still running

### ISSUE THREAD

**Issue by electricshaman** [nerves-project/nerves_runtime#3]
### Environment

* Erlang version: 19
* Elixir version: 1.4.2
* Operating system: Linux 4.4.43-v7
* Nerves Environment Info:

```
Env
  MIX_TARGET:   rpi3
  MIX_ENV:      dev

|nerves_bootstrap| Environment Package List

  Pkg:      nerves_system_br
  Vsn:      0.9.4
  Type:     system_platform
  Provider: [{Nerves.Package.Providers.HTTP, []}, {Nerves.Package.Providers.Local, []}]

  Pkg:      nerves_system_rpi3
  Vsn:      0.11.0
  Type:     system
  Provider: [{Nerves.Package.Providers.HTTP, []}, {Nerves.Package.Providers.Local, []}]

  Pkg:      nerves_toolchain_arm_unknown_linux_gnueabihf
  Vsn:      0.10.0
  Type:     toolchain
  Provider: [{Nerves.Package.Providers.HTTP, []}, {Nerves.Package.Providers.HTTP, []}]

  Pkg:      nerves_toolchain_ctng
  Vsn:      0.9.0
  Type:     toolchain_platform
  Provider: [{Nerves.Package.Providers.HTTP, []}, {Nerves.Package.Providers.Local, []}]

|nerves_bootstrap| Loadpaths Start

|nerves_bootstrap| Env Start

|nerves_bootstrap| Env End

|nerves_bootstrap| Environment Variable List
  target:     rpi3
  toolchain:  /home/jeff/.nerves/artifacts/nerves_toolchain_arm_unknown_linux_gnueabihf-0.10.0.linux-x86_64
  system:     /home/jeff/.nerves/artifacts/nerves_system_rpi3-0.11.0.arm_unknown_linux_gnueabihf
  app:        /home/jeff/Code/seedlings

|nerves_bootstrap| Loadpaths End
```

### Current behavior

The shell prompt returns to `host[x+1]` even if the executing OS process is still running.  Standard output continues to be streamed (which is good, at least you can wait for it to stop).  If the OS process requires a signal to exit, you're basically stuck.  I don't see this as being a huge problem for anyone right now since you can bail out with Erlang job control but I felt it was worth putting on record in case you ever wanted to bump the shell out of experimental status.

### Steps to Reproduce

On a Debian or Ubuntu system, execute `sudo apt-get update` in the shell.

On any target, execute `cat` without any arguments.  That one is fun.

This is happening because the BEAM port process that gets spawned is executing the target's shell at `/bin/sh` rather than user commands individually.

### Expected behavior

Ideally the shell should block while dumping standard out until the executing OS process has completed.  It would also be nice if we could pass signals to the OS process without using the tty that Erlang has already hijacked.  Maybe using a prefix key like tmux if that's even possible?  I don't know how far down that rabbit hole you want to go.  Ultimately Erlang should have priority over the tty since we are piggybacking off of its job control capabilities.

**Comment by fhunleth** [comment]
Am I understanding the issue correctly? Is the problem that `Nerves.Runtime.Shell` doesn't know when the spawned `sh` process is waiting on input? I.e., if it knew that it was waiting on input, it could give a different prompt or no prompt at all. Then when it found out that `sh` needed input again, it could provide a proper prompt. Alternatively, maybe `sh` should be invoked in interactive mode so that it can provide a prompt? I'm pretty sure that will require providing `sh` a proper tty like one can so through `tmux`, `screen` or `dtach`. Regarding `dtach`, it's really small and has a super simple Unix Domain socket interface that should let you forward things like Ctrl+C and Ctrl+D down to `sh`. I think that I agree with your statement of not knowing how far to go down the rabbit hole.

**Comment by electricshaman** [comment]
Your understanding is correct.  `Nerves.Runtime.Shell` is essentially tricking you into thinking the shell is waiting for input.  It assumes the commands executed are brief and non-blocking.  It's still possible to interact with longer running processes but the output may continue to stream back even after the prompt has returned (e.g. apt-get update will continue to list the repositories as it updates them one by one).

Another example of a side effect is that you can start up and attach to a docker container inside of it and not notice any difference at all until you start issuing commands that interrogate the system like `uname` or `whoami`.

`dtach` sounds interesting.  It also begs the question - what would happen if we started `iex` up in a terminal multiplexer like `screen` on an embedded target?  Would that even function over serial?

**Comment by fhunleth** [comment]
Regarding starting up `iex` in a terminal multiplexer, I do that with `dtach`. I'm sure that `screen` and `tmux` would work too, but I haven't tried those. The problem with the serial port is that the terminal size codes don't get sent over or aren't handled, so the terminal is stuck at 80x25. I'm guessing that there's some easy way to fix this, but I don't know it. The other problem with the serial port is that output sometimes gets dropped. Usually, it's not a big deal, but I imagine that a program that actively manages screen layout may get confused.

Fwiw, my use of `dtach` is to move the IEx console to a GUI. This is for a presentation app where when you hit F1 you get the IEx prompt so that you can do some live coding. The magic line for `erlinit` is here:
https://github.com/nerves-project/nerves_system_rpi3/blob/master/rootfs-additions/etc/erlinit.config#L15. If you build a custom system with `screen`, you could replace that line and call `screen` instead.

Getting back to the topic, try running `yes` in the `Nerves.Runtime.Shell`. Switching back to `iex` gets rid of the output, but it will eventually crash the Erlang VM when I run it.

**Comment by electricshaman** [comment]
Migrating this issue to the `nerves_runtime_shell` repo as [#1](https://github.com/nerves-project/nerves_runtime_shell/issues/1).
