### ISSUE TITLE
Move iex helpers to separate project

### ISSUE THREAD

**Issue by fhunleth** [nerves-project/nerves_runtime#32]
In prep for 1.0, I'm very interested in moving features out of our core libraries that either aren't well used or don't quite fit. The iex helpers seem to fit this bill since they're debugging convenience functions. I know that a bunch of us really like a few of these functions. It seems like we could easily move them to a separate repo and pull them in with `nerves_init_gadget` or another "starter" project. Other advantages would be that we could add more helpers without worrying about bloating everyone's projects since `nerves_runtime` is so hard to avoid as a dependency. 

I'll leave this here for a couple weeks for comments if anyone feels strongly.

**Comment by GregMefford** [comment]
The counter-point to this that I see is that, if we separate this functionality into a separate project, then we have a less-robust production troubleshooting story. For example, someone would only realize that they want these tools when they're not there in the deployed firmware that they want to troubleshoot. Maybe that's fine, but I figured it's worth bringing it up.

Either way, we should include some better documentation about this in (or referenced by) the Nerves Getting Started guide, or somewhere else that people would find it early enough in development. That way, they at least know that these tools exist and can choose to include whichever package(s) they want, if we end up having more than one.

**Comment by fhunleth** [comment]
Yeah, I'm not sure that the IEx helpers currently help with production troubleshooting. I'd really like that to change, but I don't have anything ready-to-go. 

Another way to look at this is that we separate the helpers out while we iterate on them and then when things reach a good state we consider pulling them back in to `nerves_runtime` (maybe as a dependency). I had been thinking that we'd always have them as a dep to `nerves_init_gadget`, though. I pretty much always use that project now even for boards that don't have USB gadget interfaces.

**Comment by GregMefford** [comment]
That sounds fine to me, I don't have strong feelings either way As long as we document how to accomplish the things people want to accomplish, it's nice to have separate (hopefully-appropriately-named) dependencies that they can pick and choose, in the spirit of keeping Nerves firmware minimal.

**Comment by electricshaman** [comment]
Splitting them out feels a little bit excessive to me.  I think the most intuitive place is in Nerves.Runtime as functions in a first class Helpers or Utils module that can be discovered via regular documentation methods (hexdocs, auto-completion, etc.) rather than being out-of-band in a hidden T module or whatever it’s called now.  Importing those from a module within iex is more idiomatic, IMO.  Worrying about them causing bloat smells a like bit like bikeshedding.  If we took a vote, I’d vote for moving them to a legit module and documentig the heck out of them so they can be found easily.

FWIW, I don’t always use the starter projects.  I want more control usually.  I realize I’m an outlier in that regard.  So that would be yet another dependency to remember to add manually if the helpers became indespensible.  

Responding on my phone in case this seems short/terse.
